import Head from 'next/head'
import styles from 'styles/Home.module.css'
import { styled, theme } from 'utils/stitches.config'
import type { NextPage } from 'next'

const Home: NextPage = () => {
  const Button = styled('button', {
    typography: 'body2',
    backgroundColor: '$background1',
    borderColor: '$border',
    borderWidth: '1px',
    borderRadius: '9999px',
    color: '$primary5',
    cursor: 'pointer',
    padding: '10px 15px',
    '&::after': {
      content: '',
      display: 'inline',
    },
  })
  const HeadLine = styled('h1', {
    typography: 'headline5',
    color: '$text1',
    marginBottom: '24px',
    '> a': {
      color: '$primary4',
    },
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeadLine>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </HeadLine>

        {/* eslint-disable-next-line no-constant-condition */}
        <Button type="button" className={theme.className}>
          Button 1
        </Button>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
    </div>
  )
}

export default Home
